language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - TARGET=CI
  - TARGET=IT IT_CATEGORY=Category1
  - TARGET=IT IT_CATEGORY=Category2
  - TARGET=IT IT_CATEGORY=Category3
  - TARGET=IT IT_CATEGORY=Category4
  - TARGET=IT IT_CATEGORY=Plugins
  - TARGET=POSTGRES
  - TARGET=MYSQL
  - TARGET=WEB


matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'find ~/.m2/repository -type d -name \*-SNAPSHOT -exec rm -rf {} \;'
  - 'find ~/.m2/repository -name maven-metadata-\* -exec rm {} \;'
  - 'find ~/.m2/repository -name resolver-status.properties -exec rm {} \;'

notifications:
  email: false
